### PR TITLE
Bump ember-auto-import to 2.2.4 and introduce webpack

### PR DESCRIPTION
**Pull request by SergeAstapov**
There is bunch of wins, greatly summarized by @buschtoens in https://twitter.com/buschtoens/status/1449745394594889734

### CODE REVIEW

**Review by MelSumner — CHANGES_REQUESTED** [review]
Pinging @drewlee here too

Do we think this should target a new major version branch?

**Comment by scalvert** [comment]
What would this need to be a major for, @MelSumner?

**Comment by scalvert** [comment]
Is it this:

https://github.com/ef4/ember-auto-import/blob/main/docs/upgrade-guide-2.0.md#quick-summary
> addons that upgrade to ember-auto-import >= 2 will only work in apps that have ember-auto-import >= 2, so they should do their own semver major releases when they upgrade

(I'll be honest, this dependency hell really confuses me :))

**Comment by SergeAstapov** [comment]
@scalvert yes, per above link you posted this is a breaking change hence needs a major.
If there is anything else slated for next major - I would be happy to help

**Review by scalvert — APPROVED** [review]

**Pull request merged**
