### PR TITLE
Add check for isDestroyed

### LINKED ISSUE #90: Cannot modify dependent keys for `violationClasses` on `component-name` after it has been destroyed
Hi, first of all, thanks for this awesome addon, it makes my life much better :)

I've installed this addon in my app (Ember 2.16) and when I'm browsing through pages, I got a lot of these errors into the console. 

```
"Assertion Failed: Cannot modify dependent keys for `violationClasses` on `component-name` after it has been destroyed."
```
I know what it says in general, but I'm more curious why is this happening. Is it because I'm navigating too fast? Or is it some other issue? 

Thank you,
Ondrej

### PR DESCRIPTION
**Pull request by ondrejsevcik**
Fixes #90

### CODE REVIEW

**Comment by Robdel12** [comment]
Hey @ondrejsevcik! Thank you for the PR :D I'm trying to get a passing build on travis before merging.

**Comment by ondrejsevcik** [comment]
Hi, any ideas why it's failing?

**Comment by Robdel12** [comment]
I'm not sure, I'm going to try and get to this tonight

**Comment by Robdel12** [comment]
Once #94 gets through I'd like to rebase this branch and get it merged through :)

**Comment by Robdel12** [comment]
Hm! I thought this would have auto-closed. 

I rebased your PR on top of the latest master and merged it: https://github.com/ember-a11y/ember-a11y-testing/commit/c8ee8d03386fba873c0773b04943e4626f62220a

Thank you for the contribution and sorry for the wait!

**Comment by ondrejsevcik** [comment]
No worries, thank you!

**Comment by Robdel12** [comment]
@trentmwillis when you get a chance, can you release `0.5.1`? Looks like I don't have permissions :)

**Comment by trentmwillis** [comment]
@Robdel12 I've gone ahead and published, but I also gave you permissions so that you can do future releases. On a related note, there's a `RELEASE.md` to ensure we follow the same format for releases in case you haven't seen. Feel free to update as needed.

**Pull request closed without merging**
